spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/praser_job_1
    password: admin123
    username: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: validate

linkedin:
  parsing:
    jobs:
      url: https://www.linkedin.com/jobs/search
      scroll-url: https://www.linkedin.com/jobs-guest/jobs/api/seeMoreJobPostings/search
      list:
        class-name: jobs-search__results-list
      card:
        base-card:
          class-name: base-card
          data-attributes:
            entity-urn: data-entity-urn
            tracking-id: data-tracking-id
            reference-id: data-reference-id
      full-link-class-name: base-card__full-link
      meta:
        job-title-class-name: base-search-card__title
        job-subtitle-class-name: base-search-card__subtitle
        meta-data-class-name: base-search-card__metadata
        job-time-datetime-att-name: datetime
        jobs-count-class-name: results-context-header__job-count

telegram:
  bot:
    #    id: 6909679603
    api-key: 6909679603:AAEFx4wztxj5dBgr2q7hyCjmSCwZwYsXrxg
    #    first-name: LinkedIn Bot Parser
    username: Ooshkap_LinkedIn_bot
  chat:
    id: -1002034359916
#  admin:
#    georgii:
#      id: 430443616